### ISSUE TITLE
Add module to collection for writing attachments to file system

### ISSUE THREAD

**Issue by lfvjimisola** [viczem/ansible-keepass#29]
With #27 and the move to an ansible galaxy collection we could add more functionality than just lookup.
Your project started as a lookup plugin but it could be more for KeePass.

I've written a module (follows Ansible standard and best practices, used builtin.lineinfile as model) that writes an attachment to the file system (user, group, mode, selinux stuff etc can be set as well).

Would you be interested in adding it to the collection if I create a PR? We need it for a project we have and our deadline is in 2 weeks.
Being able to use `ansible-galaxy install viczem.keepass` would be so much easier for us all.

**Comment by viczem** [comment]
Please create PR, I'll add your module to collection

**Comment by dangoncalves** [comment]
No need to write an extra module to access attached files. #30 aims to do that from the actual lookup plugin: files are retrieved from keepass entries and copied to temp files that are deleted when socket closes. (more doc on how using this feature will be added if you are interested).

Of course, if you need a permanent storage, your module could be useful.

**Comment by jimisola** [comment]
@dangoncalves That's nice. I'll provide my module for @viczem to do what he wants with it.

May I ask for some help regarding development of the collection or even better a few lines in the README.md for contributors?

I forked the repo, did a git clone, placed and updated the attachment.py under plugin. I've set COLLECTIONS_PATH (correct?):

```
jimisola@turing:~/cloud/dev/opensource/ansible_collections/viczem/keepass (feature/attachment_to_file)$ echo $COLLECTIONS_PATHS 
/home/jimisola/cloud/dev/opensource:/home/jimisola/.ansible/collections:/usr/share/ansible/collections
```

and ran ansible-test sanity checks ([here](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_testing.html#testing-tools)).

How do I (without installing the collection):
1. `ansible-doc -t lookup keepass`

```
jimisola@turing:~/cloud/dev/opensource/ansible_collections/viczem/keepass (feature/attachment_to_file)$ ansible-doc -t lookup keepass
[WARNING]: lookup keepass not found in: /home/jimisola/.ansible/plugins/lookup:/usr/share/ansible/plugins/lookup:/usr/lib/python3/dist-
packages/ansible/plugins/lookup
```

2. Run the example in doc/examples/example-playbook.yml? Tried different variants. But, since the collection is not installed it isn't found by ansible. --collections-path does not seem to work either.

```
jimisola@turing:~/cloud/dev/opensource/ansible_collections/viczem/keepass (feature/attachment_to_file)$ ansible-playbook doc/examples/example-playbook.yml --ask-vault-pass
Vault password: 
...
fatal: [127.0.0.1]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ lookup('viczem.keepass.keepass', 'spam', 'username') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: lookup plugin (viczem.keepass.keepass) not found"}
```


Finally, I've noticed that there are some typos, [wrong directory names,](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_structure.html#collection-directories-and-files) use of "plugin" instead of "collection" etc. I'll create a PR for that as well.

**Comment by dangoncalves** [comment]
Hello,

I just made [a gist](https://gist.github.com/dangoncalves/5b0ddfa2d08206af6fb5727e96404cd6) to help you installing the collection for dev purpose.

The collection works and directories names are correct see [this example](https://github.com/ansible-collections/amazon.aws)

**Comment by jimisola** [comment]
@dangoncalves Thank you for the gist!

Regarding the wrong directory, this viczem.keepass collection has `doc`while the official documentation and your provided example uses `[docs](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_structure.html#docs-directory)` (trailing 's'). I believe that those should be the same. Or perhaps it does not matter?
