### ISSUE TITLE
Long socket paths

### ISSUE THREAD

**Issue by ch-one** [viczem/ansible-keepass#3]
When using `kpsock.py` with a long path to the keepass store, the following error occurs on macOS (and probably also on linux systems):
 
```
Traceback (most recent call last):
  File "kpsock.py", line 26, in run
    s.bind(sock_file)
OSError: AF_UNIX path too long
```

I just wanted to create a pull request with a solution. Then i realized that there is a downside to my approach (1). So i thought, it would be better to discuss other posibilities.

I think about these two:
1. Put socket in `/tmp`
   * \+ Guaranteed to be short enough
   * \- Not compatibe to all systems?
2. Use python mechanism to create temporary directory (`tempfile.TemporaryDirectory()`) and place socket inside
   * \+ Compatibe to all systems
   * \- Not guaranteed to be short enough? At least under macOS i got a relatively long path (but not crittical)

@viczem what do you think about these two approaches? Do you have any other ideas to solve this?

**Comment by viczem** [comment]
Thank you for comment. I didn't know about socket path limitations. I will fix it as soon as possible

**Comment by viczem** [comment]
@ch-one I'm fix the "AF_UNIX path too long" by storing the socket file in a temporary directory (according to OS). Path of the socket file have to be predictable, because used in ansible plugin, therefore `tempfile.TemporaryDirectory()` is not a good choice.

Fixed to `"%s/ansible-keepass.sock" % tempfile.gettempdir()`. May be this is also bad solution, because no possibility to open more then one socket (e.g. two keepass data files). On the other hand, I can't imagine a use case for it.
