### ISSUE TITLE
 python kpsock.py

### ISSUE THREAD

**Issue by mohinamar** [viczem/ansible-keepass#4]
Trying to create socket file getting this error, not sure where was wrong

Traceback (most recent call last):
  File "kpsock.py", line 195, in <module>
    main(kdbx_fpath, password, kdbx_key_fpath, sock_file_path, args.ttl)
  File "kpsock.py", line 84, in main
    os.remove(sock_fpath)
OSError: [Errno 2] No such file or directory: '/tmp/ansible-keepass.sock'

**Comment by viczem** [comment]
thanks. fixed

**Comment by mohinamar** [comment]
Sorry, Still i'm getting this error
# python kpsock.py example.kdbx
Password:
2020-05-05 04:32:09 [INFO ]  Close ansible-keepass socket
Traceback (most recent call last):
  File "kpsock.py", line 196, in <module>
    main(kdbx_fpath, password, kdbx_key_fpath, sock_file_path, args.ttl)
  File "kpsock.py", line 71, in main
    except FileNotFoundError as e:
NameError: global name 'FileNotFoundError' is not defined

**Comment by mohinamar** [comment]
Thanks, Working now and also understood it works in Python3 environment only. Previously havent worked in python 2.7

**Comment by viczem** [comment]
Please add support python 2 by PR if need or use python 3.

Also I fix `FileNotFoundError is not defined`, but it is not guarantee that the script will work correctly in python 2. 

In your case socket file is not found after close, but this should not to be. Most likely the temporary folder is write protected (also was fixed by check before opening the socket)

**Comment by mohinamar** [comment]
Thanks for the prompt response, Im using it with python3
