### ISSUE TITLE
Socket location

### ISSUE THREAD

**Issue by LecrisUT** [viczem/ansible-keepass#40]
I was looking quickly at this project, and is it that this lookup creates a socket in the /tmp folder by default?
https://github.com/viczem/ansible-keepass/blob/237f3a0da53d72b04f2d04bf960e61b7fc8fcd44/plugins/lookup/keepass.py#L415

Shouldn't it be creating in /var/run/user/$(uid)/...?

**Comment by viczem** [comment]
There is nothing wrong with creating socket file in a temporary directory because `umask(0o177)` (permissions for created files will `u=rw,g=,o=` or `600`).

Also there is no guarantee that the directory you specify will exist on all operating systems. In this case using `tempfile.gettempdir` is more flexible.

You can use `ANSIBLE_KEEPASS_SOCKET` environment variable to change path of the socket file
https://github.com/viczem/ansible-keepass/blob/237f3a0da53d72b04f2d04bf960e61b7fc8fcd44/plugins/lookup/keepass.py#L412

**Comment by LecrisUT** [comment]
I was considering the difference between having the socket on hard disk vs on a ramdisk that is automatically flushed when the system crashes. But probably this is just making a mountain out of a molehill.
