### ISSUE TITLE
Cannot assign db and password variable from other variables

### ISSUE THREAD

**Issue by tkrpt5** [viczem/ansible-keepass#7]
Due to a relatively complex environment, I want to use multiple KeePass databases. This already works partially using group_vars, but I cannot represent all my combinations yet.

In order to keep the actual database path and password at one place, e.g., the group_vars, I want to override `keepass_dbx` `keepass_psw` with the intended database depending on the current task.

I have tried it the following way:
```
role_keepass_db: '/path/to/db.kdbx'
role_keepass_pwd: 'SuperSecretPassword'

keepass_dbx: "{{ role_keepass_db }}"
keepass_psw: "{{ role_keepass_pwd }}"

or

keepass_dbx: "{{ lookup('vars', 'role_keepass_db') }}"
keepass_psw: "{{ lookup('vars', 'role_keepass_pwd') }}"
```

Neither combination works, and in both cases I receive the following error:

```
FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'keepass'. Error was a <type 'exceptions.NameError'>, original message: global name 'FileNotFoundError' is not defined"}
```

A simple when statement verifies that `keepass_dbx = role_keepass_db` (same with password).

When running the task with increased verbosity, I see only the message `Keepass: fetch from kdbx file`. While a successful run would show:
```
Keepass: database file /path/to/db.kdbx
Keepass: fetch from kdbx file
KeePass: attr: password in path: test
```

It appears that `os.path.isfile(kp_dbx)` is not properly validating the path when reassigning the variable, I assume a similar problem with the password.
I am currently running Ansible using Python 2.7. As I installed ansible-keepass just last week from master, I assume to run the latest version.

Any help on this issue is appreciated :)

**Comment by viczem** [comment]
Upgrade to python 3 (python 2 is not supported)

I'm not recommend to use the plugin without UNIX socket, because each tasks will decrypt your keepass database (open - close) and it will negatively affect to performance (use kpsock.py - only one keepass databasse can be used at a time)

In my opinion, it is better to keep all entities in one keepass database relative to a project. You can create a new keepass database for use it with the plugin and paste into it (or move) needed entities from another keepass databases. It simple to do with a GUI like e.g. keepassxc

I don't know if that would be acceptable to you for keeping up-to-date a new keepass database, but from your problem description it would be more logical.

**Comment by tkrpt5** [comment]
I have now upgraded to Python3, this did not solve the problem but resulted in more usable error messages.

It turns out that the variables requested by ansible-keepass contain the "raw" value of a variable, i.e., they were not parsed by the templating engine. With the help of an awesome colleague, I have been able to add the missing template parsing. This fix uses code from an Ansible Core Module and changes only a few lines. I will submit my changes as a pull request later on.

Edit: I have submitted my pull request [here](https://github.com/viczem/ansible-keepass/pull/8).
